version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend/research-assistant
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/research-assistant:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
      - PORT=3000
    command: node .next/standalone/server.js